apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: vnw5j0ik6-nodejs 
  janus-idp.io/tekton: vnw5j0ik6-nodejs
  backstage.io/kubernetes-id: vnw5j0ik6-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vnw5j0ik6-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml