apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vnw5j0ik6-nodejs
  janus-idp.io/tekton: vnw5j0ik6-nodejs
  backstage.io/kubernetes-id: vnw5j0ik6-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vnw5j0ik6-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
